# Notebook for loading EEG data analysis


In [4]:
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
import mne
from mne.externals.pymatreader import read_mat

%matplotlib inline

In [5]:
print("MNE version: ", mne.__version__)

MNE version:  0.22.1


## Loading data

In [2]:
# Path to raw and clean data
path_raw = "Data/OriginalData/RawData/RawData_IDD/Rest/NDS001_Rest.set"
path_clean = "Data/OriginalData/CleanData/CleanData_IDD/Rest/NDS001_Rest_CD.mat"

# Example (that didn't work asd;ghjkl)
# original_data = mne.io.read_raw_fiff('original_data.fif', preload=False)
# original_info = original_data.info
# data_from_ft = mne.read_evoked_fieldtrip('evoked_data.mat', original_info)

raw_data = mne.io.read_raw_eeglab(path_raw, preload=False)

raw_info = raw_data.info
print(raw_info)
print()

# clean_data = mne.io.read_raw_fieldtrip(path_clean, raw_info, data_name="clean_data")

clean_data = read_mat(path_clean)
clean_data

Reading Data/OriginalData/RawData/RawData_IDD/Rest/NDS001_Rest.fdt
<Info | 7 non-empty values
 bads: []
 ch_names: AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4
 chs: 14 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 64.0 Hz
 meas_date: unspecified
 nchan: 14
 projs: []
 sfreq: 128.0 Hz
>



{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Wed Jan 29 17:21:37 2020',
 '__version__': '1.0',
 '__globals__': [],
 'clean_data': array([[ 1.6477047e-02, -3.2360673e+00, -2.5063744e+00, ...,
         -1.7286242e+01, -1.2736817e+01,  1.6745120e-02],
        [ 1.6743377e-02,  8.9260683e+00,  8.3895321e+00, ...,
          1.4371253e+00,  2.0206182e+00,  1.6644612e-02],
        [ 7.0179589e-03, -1.5554895e+00, -1.1901665e+00, ...,
         -4.4841924e+00, -3.4928360e+00,  7.0839487e-03],
        ...,
        [ 1.7133404e-02, -5.9072852e-01,  2.5434017e-01, ...,
         -4.7863007e+00, -2.3343065e+00,  1.7275997e-02],
        [ 1.6675107e-02,  9.0644550e-01,  1.7608433e+00, ...,
         -3.8342655e-01, -2.9413404e+00,  1.7215565e-02],
        [ 1.6772242e-02,  1.3954264e+01,  1.1846857e+01, ...,
         -1.1717071e+01, -6.1116719e+00,  1.7233258e-02]], dtype=float32)}

In [4]:
clean_data = clean_data["clean_data"]
len(clean_data)

14

In [18]:
np.shape(clean_data)[1]

15360

## Generate more training data

In [16]:
A = np.zeros((5, 50))
filter_size = 19
start = 0
end = filter_size
step = int(filter_size * 0.2)

while end < len(A[0]):
    print(A[:, start:end])
    print()
    start += step
    end += step

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [24]:
filter_size = 640  # 5 seconds
start = 0
step = int(filter_size * 0.1)  # 90% overlap

while filter_size < np.shape(clean_data)[1]:
    print(clean_data[:, start:filter_size])
    start += step
    filter_size += step

[[  0.02424849  -1.0326364   -0.03411222 ...   9.430435     7.71776
   -0.4201625 ]
 [  0.01693305  -0.68967867  -3.5956059  ...   5.7593718    8.024922
    2.4765658 ]
 [  0.02389274  -2.5375905   -2.7813148  ...  -3.5354118   -3.0739717
   -3.4311593 ]
 ...
 [  0.01244346   2.512486     1.6037483  ...  -2.650237    -3.6267335
    3.7010915 ]
 [  0.02318088 -12.021913   -11.416178   ...   1.5994077    5.240492
   -2.3732316 ]
 [  0.01928079  -0.9688771    1.2207274  ...   1.8109057    3.7473364
   -2.679689  ]]
(14, 640)

[[  4.110323    6.8587847  11.46512   ... -11.743974   -7.9149637
    5.037429 ]
 [  7.590745    8.975582    9.885472  ... -16.187569  -12.103462
   -0.1403736]
 [  2.3711905   7.128563   11.927277  ...  -7.35677    -8.807129
   -5.5890274]
 ...
 [ -6.2451653 -10.18713   -11.416644  ...  12.593639   15.300444
    9.991312 ]
 [ -2.952335   -2.2979326  -2.559906  ... -10.132344  -10.216486
   -5.3090196]
 [  5.023317    8.521797   10.179211  ... -15.01092   -14.787621
